name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - main  # Esso sarà eseguito ogni volta che fai un push su main
      
      
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # o la versione che desideri usare

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './dist'
